#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout( local_size_x = 32,local_size_y = 32, local_size_z = 1 ) in;
layout( binding = 0, rgba8 ) uniform writeonly image2D resultImage;

void main( )
{
	ivec2 pos = ivec2( gl_GlobalInvocationID.xy );
	vec4 c = vec4( gl_WorkGroupID / vec3( gl_NumWorkGroups ), 1.0 );
	imageStore( resultImage, pos, c );
}